%% Cleaning the workspace and the command window and adjusting settings
clear;clc
% changeCobraSolver('gurobi', 'LP');

%% Predict usage of underground reations
% model = readCbModel('../2_ecGEM_reconstruction/models/Kluyveromyces_marxianus-GEM.xml');
% model = buildRxnGeneMat(model);
% model = ravenCobraWrapper(model);
% model = buildRxnGeneMat(model);

load('Kluyveromyces_marxianus-GEM.mat');
% load('../2_ecGEM_reconstruction/models/ecKmarx.mat');

%% Define constraints and other parameters

% Verduyn medium without carbon
exchangeIndex = find(contains(model.rxnNames, "exchange"));
exchangeIDs = model.rxns(exchangeIndex);
exchangeIDs(end) = [];

Verduyn_components = ["r_1723", "r_1724", "r_1725", ...
    "r_1727", "r_1728", "r_1729", ...
    "r_1730", "r_1731", "r_1732", ...
    "r_1734", "r_1735", "r_1736"];

model = changeRxnBounds(model, exchangeIDs, 0, 'l');
model = changeRxnBounds(model, Verduyn_components, -1000, 'l');

model = changeObjective(model, 'r_1913', 1);

% model = changeRxnBounds(model, "r_1726", -5, 'l'); % glucose
model = changeRxnBounds(model, "r_1726", 0, 'l'); % glucose
model = changeRxnBounds(model, "r_1856", -3, 'l'); % lactose
% model = changeRxnBounds(model, "r_1795", -7, 'l'); % xylose

model = changeRxnBounds(model, 'r_1759', 0, 'u');
model = changeRxnBounds(model, 'r_1758', 0, 'u');
model = changeRxnBounds(model, 'r_1878', 0, 'u');

solution = optimizeCbModel(model);
printFluxes(model, solution.x, true);


%% Run PROM
normCounts0h = readtable("Diniz2017_normcounts_0h.csv", "ReadVariableNames", true);

expressedGenes = normCounts0h.Gene;

normCounts0h = removevars(normCounts0h, "Gene");
normCounts0h = table2array(normCounts0h);

TRN = readtable("Diniz2017_TRN_concat.csv", "Delimiter", "\t");

tic
[f_0h,f_ko_0h,v_0h,v_ko_0h,status1_0h,lostxns_0h,probtfgene_0h,bnumstobekoed_0h] = promv2(model, ...
                                                                                          normCounts0h, ...
                                                                                          expressedGenes, ...
                                                                                          TRN.Regulator, ...
                                                                                          TRN.Target, ...
                                                                                          '','','','', ...
                                                                                          '','','','','' ...
                                                                                          ,0);

[fOE_0h,fOE_ko_0h,vOE_0h,vOE_ko_0h,status1OE_0h,lostxnsOE_0h,probtfgeneOE_0h,bnumstobekoedOE_0h] = promv2TFOE(model, ...
                                                                                          normCounts0h, ...
                                                                                          expressedGenes, ...
                                                                                          TRN.Regulator, ...
                                                                                          TRN.Target, ...
                                                                                          '','','','','', ...
                                                                                          '','','','','', ...
                                                                                          '',0);

normCounts1h = readtable("Diniz2017_normcounts_1h.csv", "ReadVariableNames", true);
normCounts1h = removevars(normCounts1h, "Gene");
normCounts1h = table2array(normCounts1h);

model = changeRxnBounds(model, "r_1803", 9, 'l'); % ethanol

[f_1h,f_ko_1h,v_1h,v_ko_1h,status1_1h,lostxns_1h,probtfgene_1h,bnumstobekoed_1h] = promv2(model, ...
                                                                                          normCounts1h, ...
                                                                                          expressedGenes, ...
                                                                                          TRN.Regulator, ...
                                                                                          TRN.Target, ...
                                                                                          '','','','', ...
                                                                                          '','','','','' ...
                                                                                          ,0);

[fOE_1h,fOE_ko_1h,vOE_1h,vOE_ko_1h,status1OE_1h,lostxnsOE_1h,probtfgeneOE_1h,bnumstobekoedOE_1h] = promv2TFOE(model, ...
                                                                                          normCounts1h, ...
                                                                                          expressedGenes, ...
                                                                                          TRN.Regulator, ...
                                                                                          TRN.Target, ...
                                                                                          '','','','','', ...
                                                                                          '','','','','', ...
                                                                                          '',0);


normCounts4h = readtable("Diniz2017_normcounts_4h.csv", "ReadVariableNames", true);
normCounts4h = removevars(normCounts4h, "Gene");
normCounts4h = table2array(normCounts4h);

[f_4h,f_ko_4h,v_4h,v_ko_4h,status1_4h,lostxns_4h,probtfgene_4h,bnumstobekoed_4h] = promv2(model, ...
                                                                                          normCounts4h, ...
                                                                                          expressedGenes, ...
                                                                                          TRN.Regulator, ...
                                                                                          TRN.Target, ...
                                                                                          '','','','', ...
                                                                                          '','','','','' ...
                                                                                          ,0);

[fOE_4h,fOE_ko_4h,vOE_4h,vOE_ko_4h,status1OE_4h,lostxnsOE_4h,probtfgeneOE_4h,bnumstobekoedOE_4h] = promv2TFOE(model, ...
                                                                                          normCounts4h, ...
                                                                                          expressedGenes, ...
                                                                                          TRN.Regulator, ...
                                                                                          TRN.Target, ...
                                                                                          '','','','','', ...
                                                                                          '','','','','', ...
                                                                                          '',0);

toc

%%
