%% Cleaning the workspace and the command window and adjusting settings
clear;clc
% changeCobraSolver('gurobi', 'LP');

%% Predict usage of underground reations
% model = readCbModel('../2_ecGEM_reconstruction/models/Kluyveromyces_marxianus-GEM.xml');
% model = buildRxnGeneMat(model);
% model = ravenCobraWrapper(model);
% model = buildRxnGeneMat(model);

load('Kluyveromyces_marxianus-GEM.mat');
% load('../2_ecGEM_reconstruction/models/ecKmarx.mat');

%% Define constraints and other parameters

% Verduyn medium without carbon
exchangeIndex = find(contains(model.rxnNames, "exchange"));
exchangeIDs = model.rxns(exchangeIndex);
exchangeIDs(end) = [];

Verduyn_components = ["r_1723", "r_1724", "r_1725", ...
    "r_1727", "r_1728", "r_1729", ...
    "r_1730", "r_1731", "r_1732", ...
    "r_1734", "r_1735", "r_1736"];

model = changeRxnBounds(model, exchangeIDs, 0, 'l');
model = changeRxnBounds(model, Verduyn_components, -1000, 'l');

model = changeObjective(model, 'r_1913', 1);

% model = changeRxnBounds(model, "r_1726", -5, 'l'); % glucose
model = changeRxnBounds(model, "r_1726", 0, 'l'); % glucose
% model = changeRxnBounds(model, "r_1856", -3, 'l'); % lactose
model = changeRxnBounds(model, "r_1795", -3, 'l'); % xylose

% model = changeRxnBounds(model, 'r_1759', 0, 'u');
% model = changeRxnBounds(model, 'r_1758', 0, 'u');
% model = changeRxnBounds(model, 'r_1878', 0, 'u');

solution = optimizeCbModel(model);
printFluxes(model, solution.x, true);


%% Run PROM
normCounts0km = readtable("Mo2019_normcounts_0KM.csv", "ReadVariableNames", true);

expressedGenes = normCounts0km.Gene;

normCounts0km = removevars(normCounts0km, "Gene");
normCounts0km = table2array(normCounts0km);

TRN = readtable("Mo2019_TRN_concat.csv", "Delimiter", "\t");

tic
[f_0km,f_ko_0km,v_0km,v_ko_0km,status1_0km,lostxns_0km,probtfgene_0km,bnumstobekoed_0km] = promv2(model, ...
                                                                                          normCounts0km, ...
                                                                                          expressedGenes, ...
                                                                                          TRN.Regulator, ...
                                                                                          TRN.Target, ...
                                                                                          '','','','', ...
                                                                                          '','','','','' ...
                                                                                          ,0);

[fOE_0km,fOE_ko_0km,vOE_0km,vOE_ko_0km,status1OE_0km,lostxnsOE_0km,probtfgeneOE_0km,bnumstobekoedOE_0km] = promv2TFOE(model, ...
                                                                                          normCounts0km, ...
                                                                                          expressedGenes, ...
                                                                                          TRN.Regulator, ...
                                                                                          TRN.Target, ...
                                                                                          '','','','','', ...
                                                                                          '','','','','', ...
                                                                                          '',0);

normCounts0100d = readtable("Mo2019_normcounts_0100d.csv", "ReadVariableNames", true);
normCounts0100d = removevars(normCounts0100d, "Gene");
normCounts0100d = table2array(normCounts0100d);

[f_0100d,f_ko_0100d,v_0100d,v_ko_0100d,status1_0100d,lostxns_0100d,probtfgene_0100d,bnumstobekoed_0100d] = promv2(model, ...
                                                                                          normCounts0100d, ...
                                                                                          expressedGenes, ...
                                                                                          TRN.Regulator, ...
                                                                                          TRN.Target, ...
                                                                                          '','','','', ...
                                                                                          '','','','','' ...
                                                                                          ,0);

[fOE_0100d,fOE_ko_0100d,vOE_0100d,vOE_ko_0100d,status1OE_0100d,lostxnsOE_0100d,probtfgeneOE_0100d,bnumstobekoedOE_0100d] = promv2TFOE(model, ...
                                                                                          normCounts0100d, ...
                                                                                          expressedGenes, ...
                                                                                          TRN.Regulator, ...
                                                                                          TRN.Target, ...
                                                                                          '','','','','', ...
                                                                                          '','','','','', ...
                                                                                          '',0);

model = changeRxnBounds(model, "r_1803", 5, 'l'); % ethanol

normCounts4km = readtable("Mo2019_normcounts_4KM.csv", "ReadVariableNames", true);
normCounts4km = removevars(normCounts4km, "Gene");
normCounts4km = table2array(normCounts4km);

[f_4km,f_ko_4km,v_4km,v_ko_4km,status1_4km,lostxns_4km,probtfgene_4km,bnumstobekoed_4km] = promv2(model, ...
                                                                                          normCounts4km, ...
                                                                                          expressedGenes, ...
                                                                                          TRN.Regulator, ...
                                                                                          TRN.Target, ...
                                                                                          '','','','', ...
                                                                                          '','','','','' ...
                                                                                          ,0);

[fOE_4km,fOE_ko_4km,vOE_4km,vOE_ko_4km,status1OE_4km,lostxnsOE_4km,probtfgeneOE_4km,bnumstobekoedOE_4km] = promv2TFOE(model, ...
                                                                                          normCounts4km, ...
                                                                                          expressedGenes, ...
                                                                                          TRN.Regulator, ...
                                                                                          TRN.Target, ...
                                                                                          '','','','','', ...
                                                                                          '','','','','', ...
                                                                                          '',0);

normCounts4100d = readtable("Mo2019_normcounts_4100d.csv", "ReadVariableNames", true);
normCounts4100d = removevars(normCounts4100d, "Gene");
normCounts4100d = table2array(normCounts4100d);

[f_4100d,f_ko_4100d,v_4100d,v_ko_4100d,status1_4100d,lostxns_4100d,probtfgene_4100d,bnumstobekoed_4100d] = promv2(model, ...
                                                                                          normCounts4100d, ...
                                                                                          expressedGenes, ...
                                                                                          TRN.Regulator, ...
                                                                                          TRN.Target, ...
                                                                                          '','','','', ...
                                                                                          '','','','','' ...
                                                                                          ,0);

[fOE_4100d,fOE_ko_4100d,vOE_4100d,vOE_ko_4100d,status1OE_4100d,lostxnsOE_4100d,probtfgeneOE_4100d,bnumstobekoedOE_4100d] = promv2TFOE(model, ...
                                                                                          normCounts4100d, ...
                                                                                          expressedGenes, ...
                                                                                          TRN.Regulator, ...
                                                                                          TRN.Target, ...
                                                                                          '','','','','', ...
                                                                                          '','','','','', ...
                                                                                          '',0);

normCounts6km = readtable("Mo2019_normcounts_6KM.csv", "ReadVariableNames", true);
normCounts6km = removevars(normCounts6km, "Gene");
normCounts6km = table2array(normCounts6km);

[f_6km,f_ko_6km,v_6km,v_ko_6km,status1_6km,lostxns_6km,probtfgene_6km,bnumstobekoed_6km] = promv2(model, ...
                                                                                          normCounts6km, ...
                                                                                          expressedGenes, ...
                                                                                          TRN.Regulator, ...
                                                                                          TRN.Target, ...
                                                                                          '','','','', ...
                                                                                          '','','','','' ...
                                                                                          ,0);

[fOE_6km,fOE_ko_6km,vOE_6km,vOE_ko_6km,status1OE_6km,lostxnsOE_6km,probtfgeneOE_6km,bnumstobekoedOE_6km] = promv2TFOE(model, ...
                                                                                          normCounts6km, ...
                                                                                          expressedGenes, ...
                                                                                          TRN.Regulator, ...
                                                                                          TRN.Target, ...
                                                                                          '','','','','', ...
                                                                                          '','','','','', ...
                                                                                          '',0);

normCounts6100d = readtable("Mo2019_normcounts_6100d.csv", "ReadVariableNames", true);
normCounts6100d = removevars(normCounts6100d, "Gene");
normCounts6100d = table2array(normCounts6100d);

[f_6100d,f_ko_6100d,v_6100d,v_ko_6100d,status1_6100d,lostxns_6100d,probtfgene_6100d,bnumstobekoed_6100d] = promv2(model, ...
                                                                                          normCounts6100d, ...
                                                                                          expressedGenes, ...
                                                                                          TRN.Regulator, ...
                                                                                          TRN.Target, ...
                                                                                          '','','','', ...
                                                                                          '','','','','' ...
                                                                                          ,0);

[fOE_6100d,fOE_ko_6100d,vOE_6100d,vOE_ko_6100d,status1OE_6100d,lostxnsOE_6100d,probtfgeneOE_6100d,bnumstobekoedOE_6100d] = promv2TFOE(model, ...
                                                                                          normCounts6100d, ...
                                                                                          expressedGenes, ...
                                                                                          TRN.Regulator, ...
                                                                                          TRN.Target, ...
                                                                                          '','','','','', ...
                                                                                          '','','','','', ...
                                                                                          '',0);

toc